batch_size: 16
height: 96
learning_rate: 0.0005
max_text_length: 68
model_path: models/202512170920
train_epochs: 50
train_workers: 20
vocab: " '/123456789ABCDEFGHIJKLMNOPQRSTUVWXYabcdefghiklmnopqrstuvxyz\xC1\xC2\xCD\xD3\
  \xD4\xDD\xE0\xE1\xE2\xE3\xE8\xE9\xEA\xEC\xED\xF2\xF3\xF4\xF5\xF9\xFA\xFD\u0103\u0110\
  \u0111\u0129\u0169\u01A1\u01AF\u01B0\u1EA1\u1EA2\u1EA3\u1EA4\u1EA5\u1EA7\u1EA9\u1EAB\
  \u1EAD\u1EAF\u1EB1\u1EB3\u1EB5\u1EB7\u1EB9\u1EBB\u1EBD\u1EBF\u1EC1\u1EC3\u1EC5\u1EC7\
  \u1EC9\u1ECB\u1ECD\u1ECF\u1ED1\u1ED3\u1ED4\u1ED5\u1ED7\u1ED9\u1EDB\u1EDD\u1EDE\u1EDF\
  \u1EE1\u1EE3\u1EE5\u1EE7\u1EE8\u1EE9\u1EEB\u1EED\u1EEF\u1EF1\u1EF3\u1EF5\u1EF7\u1EF9"
width: 1024
